[package]
name = "rcin"
version = "0.1.0"
authors = ["dranikpg"]
license="MIT"
edition = "2018"

description="Functions for prototyping with cin like input"
keywords=["input"]

homepage="https://github.com/dranikpg/rcin"
readme = "README.md"

[dependencies]
lazy_static = "^1.4.0"
